fix missing images

diff --git a/.github/push-all b/.github/push-all
--- a/.github/push-all
+++ b/.github/push-all
@@ -10,6 +10,12 @@ SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 REPOS=$@
 
 function push_image {
+
+    if ! docker image exists "${IMAGE_NAME}:${1}"; then
+        echo "Skipping missing version: $1"
+        return
+    fi
+
     echo -n "Pushing $1: "
 
     for repo in "$REPOS"; do
